/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_ZIGBEE_PB_H_INCLUDED
#define PB_ZIGBEE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SwZb_t {
    uint64_t deviceID;
    uint32_t endpoint;
    bool status;
} SwZb_t;

typedef struct _Zigbee_t {
    bool has_sw;
    SwZb_t sw;
    bool sync;
} Zigbee_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Zigbee_t_init_default                    {false, SwZb_t_init_default, 0}
#define SwZb_t_init_default                      {0, 0, 0}
#define Zigbee_t_init_zero                       {false, SwZb_t_init_zero, 0}
#define SwZb_t_init_zero                         {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SwZb_t_deviceID_tag                      1
#define SwZb_t_endpoint_tag                      2
#define SwZb_t_status_tag                        3
#define Zigbee_t_sw_tag                          1
#define Zigbee_t_sync_tag                        2

/* Struct field encoding specification for nanopb */
#define Zigbee_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sw,                1) \
X(a, STATIC,   SINGULAR, BOOL,     sync,              2)
#define Zigbee_t_CALLBACK NULL
#define Zigbee_t_DEFAULT NULL
#define Zigbee_t_sw_MSGTYPE SwZb_t

#define SwZb_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   deviceID,          1) \
X(a, STATIC,   SINGULAR, UINT32,   endpoint,          2) \
X(a, STATIC,   SINGULAR, BOOL,     status,            3)
#define SwZb_t_CALLBACK NULL
#define SwZb_t_DEFAULT NULL

extern const pb_msgdesc_t Zigbee_t_msg;
extern const pb_msgdesc_t SwZb_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Zigbee_t_fields &Zigbee_t_msg
#define SwZb_t_fields &SwZb_t_msg

/* Maximum encoded size of messages (where known) */
#define SwZb_t_size                              19
#define ZIGBEE_PB_H_MAX_SIZE                     Zigbee_t_size
#define Zigbee_t_size                            23

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
