/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "zigbee.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Zigbee_t, Zigbee_t, AUTO)


PB_BIND(SwZb_t, SwZb_t, AUTO)



